dev:
  image: starefossen/github-pages
  command: jekyll serve --watch --incremental
  ports:
    - 4000:4000
  volumes:
    - .:/usr/src/app

build:
  image: jekyll/jekyll:pages
  command: jekyll build
  volumes:
    - .:/usr/src/app
